export { default as MainContainer } from './main-container'
export { default as SEO } from './seo'
export { default as Rectangle } from './rectangle'
export { default as Container } from './container'
export { default as Heading } from './heading'
export { default as Caption } from './caption'
export { default as Paragraph } from './paragraph'
