export { default as Header } from './header'
export { default as Skills } from './skills'
export { default as Projects } from './projects'
export { default as Footer } from './footer'
export { default as Nav } from './nav' 
